import os
import mistune
import subprocess
from flask import Flask, render_template, request, jsonify

# --- Flask App ---
# Initialize Flask to look for templates in the 'templates' directory
app = Flask("docserver")

# --- Core AI Logic ---
def call_ai_analyzer(code_snippet):
    """
    Placeholder for calling an AI tool (e.g., cline cli) to explain a code snippet.
    This mock implementation returns a generic response.
    """
    prompt = f"Please provide a detailed explanation for the following code snippet. Focus on its purpose, how it works, and potential use cases. The audience is another developer.\n\n```\n{code_snippet}\n```"
    print(f"--- AI PROMPT ---\n{prompt}\n-----------------")
    
    # In a real implementation, you would use subprocess to call an external tool:
    # result = subprocess.run(['cline', 'ask', prompt], capture_output=True, text=True)
    # explanation_md = result.stdout
    
    # Mock response for now:
    explanation_md = f"""
# AI Code Explanation

Here is a breakdown of the code you provided:

## Purpose
This section would describe the high-level goal of the code. It appears to be a Python script using the Flask web framework.

## Key Components
- **Function/Class 1**: A detailed explanation of the first major part of the code.
- **Variable `foo`**: What this variable is used for.
- **Logic Block**: How the main conditional or loop works.

## Use Case
A typical use case for this code would be to serve as a web endpoint in a larger application. For example, it could handle user authentication or data processing.

---
*This explanation was generated by a mock AI.*
"""
    return explanation_md

# --- Flask Routes ---
@app.route("/")
def index():
    """Renders the main demo page."""
    return render_template("index.html")

@app.route("/api/explain", methods=["POST"])
def explain_code():
    """
    API endpoint that receives code, gets an explanation from the AI,
    and returns it as HTML.
    """
    data = request.get_json()
    if not data or "code" not in data:
        return jsonify({"error": "No code provided"}), 400
    
    code_snippet = data["code"]
    
    # Get the explanation in Markdown format
    explanation_md = call_ai_analyzer(code_snippet)
    
    # Convert Markdown to HTML for direct rendering on the frontend
    explanation_html = mistune.html(explanation_md)
    
    return jsonify({"explanation_html": explanation_html})

# --- Main Execution ---
def main():
    """Runs the Flask web server for the demo."""
    print("Starting DocServer Demo at http://127.0.0.1:5000")
    # Use os.environ.get to be compatible with production servers like Gunicorn
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=True)

if __name__ == "__main__":
    main()
